### ISSUE TITLE
RServices Installation Nightmare

### ISSUE THREAD

**Issue by wbuchanan** [Microsoft/tigertoolbox#26] opened 2017-02-02 12:22 UTC
Hey,

I followed all the installation instructions to install RServices on an instance of SQL Server 2016 Standard, but continue to get a fairly uninformative error when ever I try the test case (the hello 1 thing) saying it can't communicate with MS Launchpad service.  When I look at the error log it says it can't close the connection.  I've tried looking up info to fix things every where I can think of but still have no luck.  Was hoping maybe some of the folks here might be able to give me an idea of what to try or how to get someone on the phone/screen share to help me fix the problem?

**Comment by amitmsft** [comment] 2017-02-03 07:17
You could post the question on https://social.msdn.microsoft.com/Forums/en-US/home?forum=MicrosoftR or open a support incident if the issue is related to a production environment at https://support.microsoft.com/en-us/gp/contactus81?Audience=Commercial

**Comment by amitmsft** [comment] 2017-02-03 07:17
I am closing this issue as this is not related to this GitHub repo.

**Closed by amitmsft** 2017-02-03 07:17 UTC
